"""The generated ``README.md`` of a dataset folder: the dataset card, the evidence and the build record.

GitHub shows a folder's ``README.md`` below its file list, so this page is what a visitor of the folder sees.
It is generated, never edited by hand: :meth:`~data_foundry.v2.dataset.AbstractCuratedDataset.check`
rewrites it, and only :meth:`~data_foundry.v2.dataset.AbstractCuratedDataset.build` writes a new build record.

The YAML frontmatter is the machine-readable part: the build record (UUID, checksum, provenance), the data and
split shape, the grouping of a grouped task, and the bundle-check outcome. GitHub renders it as a table at the top
of the page, so it holds short values only. The body explains the folder (its files, links, how to rebuild), then
gives the dataset and task, the curation notes, the splits, the group structure of a grouped task, the decisions with
their evidence, the bundle checks, the data-check tables and the build record. The page has no timestamp outside the
build record, so an unchanged dataset gives an unchanged file.
"""

from __future__ import annotations

import datetime as dt
import os
import re
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pandas as pd
import yaml

from data_foundry.curation._paths import records_dir, resolve_curation_root
from data_foundry.schema import resolve_warehouse_dir
from data_foundry.v2 import group_checks
from data_foundry.v2.dataset import CLI_COMMAND, DEFINITION_FILENAME, REPORT_FILENAME, provenance, split_summary

if TYPE_CHECKING:
    from data_foundry.v2.dataset import AbstractCuratedDataset, CurationResult

REPORT_FORMAT = "data-foundry-report-v2"
"""Identifies the frontmatter layout, for readers that parse it."""

FIGURE_DIR = "figures"
"""Folder next to ``README.md`` that holds the decision figures."""

WORKBENCH_FILENAME = "explore.ipynb"
"""The workbench notebook of a dataset folder."""

MAX_TABLE_ROWS = 60
"""Rows shown per table in the body; the rest is summarised in one line."""

MAX_CELL_CHARS = 80
"""Characters shown per table cell in the body."""

MAX_OPEN_ROWS = 10
"""Generated tables with more rows than this are collapsed into a ``<details>`` block."""

PROBLEM_TYPES = {
    "binary_classification": "Binary classification",
    "multiclass_classification": "Multiclass classification",
    "regression": "Regression",
}

FILE_DESCRIPTIONS = {
    DEFINITION_FILENAME: (
        "The definition, and the only file edited by hand: metadata, reading and cleaning the raw files, feature "
        "types and splits."
    ),
    WORKBENCH_FILENAME: "The workbench for looking at the data, with its outputs committed. Not needed to rebuild.",
    REPORT_FILENAME: "This page, generated by `dataset check` and `dataset build`.",
    FIGURE_DIR: "The figures of the decisions below, generated with this page.",
}


def read_report(path: Path | str) -> dict[str, Any]:
    """Return the frontmatter of a generated ``README.md`` (an empty dict for a missing file or no frontmatter)."""
    path = Path(path)
    if not path.is_file():
        return {}
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    return yaml.safe_load(text[4:end]) or {}


def report_frontmatter(result: CurationResult, *, previous: dict[str, Any] | None = None) -> dict[str, Any]:
    """Build the machine-readable frontmatter for ``result``.

    ``previous`` is the frontmatter of the page being replaced; a check keeps its build record and flags it
    stale when the checksum changed.
    """
    container = result.container
    ds = result.dataset
    task = container.task_metadata
    splits_meta = container.experiment_metadata
    df = container.dataset
    report = result.bundle_report

    if result.saved:
        build = {
            "uuid": container.uuid,
            "checksum": container.checksum,
            "built_at": result.created_at.replace(microsecond=0).isoformat(),
            "path": result.saved_path.relative_to(resolve_warehouse_dir()).as_posix(),
            **provenance(ds.folder),
        }
    else:
        build = (previous or {}).get("build")

    sizes = split_summary(df, splits_meta.splits)
    grouping = None
    if task.grouping is not None:
        grouping = {
            "prediction_unit": task.grouping.prediction_unit,
            "aggregation": task.grouping.aggregation,
            "context": task.grouping.context,
        }
        if result.group_stats is not None:
            low, high = result.group_stats.test_groups_per_fold
            grouping |= {"n_groups": result.group_stats.n_groups, "test_groups_per_fold": {"min": low, "max": high}}
    return {
        "report_format": REPORT_FORMAT,
        "unique_name": container.dataset_metadata.unique_name,
        "container_format": container.format_version,
        "checksum": container.checksum,
        "build": build,
        "build_stale": bool(build) and build.get("checksum") != container.checksum,
        "data": {
            "n_rows": len(df),
            "n_features": int(df.shape[1] - 1),
            "dtypes": {str(k): int(v) for k, v in df.dtypes.astype(str).value_counts().sort_index().items()},
            "n_test_dataset_rows": None if container.test_dataset is None else len(container.test_dataset),
        },
        "task": {
            "target": task.target_column_name,
            "problem_type": task.problem_type,
            "metric": task.objective_metric_name,
            "split_regime": task.split_regime,
            "stratify_on": task.stratify_on,
            "time_on": task.time_on,
            "group_on": task.group_on,
            "group_labels": task.group_labels,
            "group_time_on": task.group_time_on,
            "grouping": grouping,
        },
        "splits": {
            "n_repeats": len(splits_meta.splits),
            "n_folds": len(next(iter(splits_meta.splits.values()))),
            "random_state": splits_meta.split_random_state,
            "time_horizon": splits_meta.time_horizon,
            "time_horizon_unit": splits_meta.time_horizon_unit,
            "n_train": {"min": int(sizes["n_train"].min()), "max": int(sizes["n_train"].max())},
            "n_test": {"min": int(sizes["n_test"].min()), "max": int(sizes["n_test"].max())},
        },
        "bundle_checks": {
            "ok": report.ok,
            "errors": [r.slug for r in report.errors],
            "warnings": [r.slug for r in report.warnings],
            "infos": [r.slug for r in report.infos],
            "accepted": dict(ds.accepted_check_warnings),
        },
        "decisions": [d.title for d in result.decisions],
    }


def render_report(
    result: CurationResult,
    *,
    previous: dict[str, Any] | None = None,
    figures: dict[int, str] | None = None,
) -> str:
    """Render the full ``README.md`` text for ``result`` (``figures``: decision index -> relative PNG path)."""
    figures = figures or {}
    fm = report_frontmatter(result, previous=previous)
    out: list[str] = ["---", yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).rstrip(), "---", ""]
    out += _header(result, fm)
    out += _files_section(result.dataset, has_figures=bool(figures))
    out += _rebuild_section(result.dataset)
    out += _dataset_section(result, fm)
    out += _curation_notes_section(result)
    out += _splits_section(result, fm)
    out += _group_section(result)
    out += _decisions_section(result, figures)
    out += _bundle_checks_section(result)
    out += _data_checks_section(result)
    out += _build_section(fm)
    return "\n".join(out).rstrip() + "\n"


# --- sections -----------------------------------------------------------------------------------------------


def _header(result: CurationResult, fm: dict[str, Any]) -> list[str]:
    meta = result.container.dataset_metadata
    task = fm["task"]
    data = fm["data"]
    regime = {
        "temporal_non_iid": f"temporal splits by `{task['time_on']}`",
        "grouped_non_iid": f"grouped splits by {_names(task['group_on'])}",
    }.get(task["split_regime"], "IID splits")
    grouping = task.get("grouping") or {}
    if grouping.get("prediction_unit") == "group":
        regime += f", one prediction per group ({grouping['aggregation']})"
    size = f"{data['n_rows']:,} rows and {data['n_features']:,} features"
    if data["n_test_dataset_rows"]:
        size += f", plus {data['n_test_dataset_rows']:,} unlabeled test rows"
    summary = (
        f"{PROBLEM_TYPES.get(task['problem_type'], task['problem_type'])} of `{task['target']}`, scored with "
        f"`{task['metric']}` on {regime}. {size}. Source: {meta.dataset_source} ({meta.dataset_year})."
    )
    return [
        f"# {meta.unique_name}",
        "",
        f"> Generated from [`{DEFINITION_FILENAME}`]({DEFINITION_FILENAME}) by `dataset check` "
        f"(or `build`). Do not edit this page: change `{DEFINITION_FILENAME}` and re-run the check.",
        "",
        summary,
        "",
        _status_line(fm),
        "",
    ]


def _status_line(fm: dict[str, Any]) -> str:
    build = fm["build"]
    if not build:
        return f"Not built yet. The current definition gives checksum `{fm['checksum']}`."
    built = f"Built as `{build['uuid']}` on {str(build.get('built_at', ''))[:10]}"
    if fm["build_stale"]:
        return (
            f"{built}, but `{DEFINITION_FILENAME}` has changed since: it now gives checksum `{fm['checksum']}`, "
            "so the build is stale. See [Build](#build)."
        )
    return f"{built}. See [Build](#build)."


def _files_section(ds: AbstractCuratedDataset, *, has_figures: bool) -> list[str]:
    folder = ds.folder
    present = {p.name: p for p in folder.iterdir() if not p.name.startswith(".") and p.name != "__pycache__"}
    known = [DEFINITION_FILENAME, WORKBENCH_FILENAME, REPORT_FILENAME, FIGURE_DIR]
    rows = []
    for name in known:
        shown = name == REPORT_FILENAME or (name == FIGURE_DIR and has_figures) or name in present
        if shown and name != FIGURE_DIR:
            rows.append((f"[`{name}`]({name})", FILE_DESCRIPTIONS[name]))
        elif shown:
            rows.append((f"[`{name}/`]({name})", FILE_DESCRIPTIONS[name]))
    definition = (folder / DEFINITION_FILENAME).read_text() if DEFINITION_FILENAME in present else ""
    for name in sorted(set(present) - set(known)):
        path = present[name]
        if name in definition:
            what = f"Read by `{DEFINITION_FILENAME}`."
        else:
            what = f"Next to the definition, but `{DEFINITION_FILENAME}` does not name it."
        rows.append((f"[`{name}/`]({name})" if path.is_dir() else f"[`{name}`]({name})", what))
    out = ["## Files in this folder", "", _table(pd.DataFrame(rows, columns=["file", "what it is"]), full=True), ""]

    links = []
    record = _record_link(ds)
    if record:
        links.append(f"- The curation record, with the triage decision and its sources: {record}")
    links.append(f"- The original source: <{ds.dataset_metadata.original_dataset_source_download_link}>")
    collection = [
        f"[`{folder.parent.name}/{name}`](../{name})"
        for name in ("README.md", "CHANGELOG.md")
        if (folder.parent / name).is_file()
    ]
    if collection:
        links.append(f"- The collection this folder belongs to: {' and '.join(collection)}")
    return [*out, *links, ""]


def _rebuild_section(ds: AbstractCuratedDataset) -> list[str]:
    meta = ds.dataset_metadata
    raw = f"local-data-warehouse/{ds.raw_dir.name}/"
    out = ["## Rebuild", "", f"`{DEFINITION_FILENAME}` reads its raw files from `{raw}`. To get them:", ""]
    out += [_fence(meta.download_description, "text"), ""]
    if ds.prepared_raw_files:
        files = ", ".join(f"`{f}`" for f in ds.prepared_raw_files)
        out += [f"On first use, `_prepare_raw_files` writes {files} into the same folder.", ""]
    target = _repo_relative(ds.folder)
    out += [
        "Then, from the repository root:",
        "",
        _fence(
            f"{CLI_COMMAND} dataset check {target}   # pipeline and checks, no UUID; rewrites this page\n"
            f"{CLI_COMMAND} dataset build {target}   # also saves the container and records its UUID",
            "bash",
        ),
        "",
        "Only curators run `build`, when the dataset ships.",
        "",
    ]
    return out


def _dataset_section(result: CurationResult, fm: dict[str, Any]) -> list[str]:
    container = result.container
    meta = container.dataset_metadata
    df = container.dataset
    rows = [
        ("source", f"{meta.dataset_source}: {meta.original_dataset_source_download_link}"),
        ("year", meta.dataset_year),
        ("domain", meta.domain_str),
        ("license", meta.license),
        ("data_tags", ", ".join(meta.data_tags)),
        ("reference", meta.academic_reference_bibtex_key),
    ]
    if meta.version_from_unique_name:
        rows.append(("version of", meta.version_from_unique_name))
    rows += [("rows x columns", f"{df.shape[0]:,} x {df.shape[1]:,}")]
    rows += [(f"task.{k}", v) for k, v in fm["task"].items() if v is not None and k != "grouping"]
    out = ["## Dataset and task", "", _table(pd.DataFrame(rows, columns=["field", "value"]), full=True), ""]

    types = result.dataset.feature_types(df)
    present = set(df.columns)  # a custom split step may drop columns after `_feature_types` named them
    groups = [
        ("categorical", [c for c in types.categorical if c in present]),
        ("string", [c for c in types.string if c in present]),
        ("datetime", [f"{c} ({f})" if f else c for c, f in types.datetime_formats.items() if c in present]),
    ]
    lines = [
        f"- {kind} ({len(cols)}): {', '.join(f'`{c}`' for c in cols) if cols else 'none'}" for kind, cols in groups
    ]
    counts = ", ".join(f"{len(cols)} {kind}" for kind, cols in groups)
    out += _details(f"Feature types: {counts}", "\n".join(lines))
    out += _details("BibTeX", _fence(meta.academic_reference_bibtex, "bibtex"))
    return out


def _curation_notes_section(result: CurationResult) -> list[str]:
    meta = result.container.dataset_metadata
    out = []
    if meta.curation_comments and meta.curation_comments.strip():
        out += [meta.curation_comments.strip(), ""]
    if meta.version_comment and meta.version_comment.strip():
        out += [f"Version of `{meta.version_from_unique_name}`: {_one_line(meta.version_comment)}", ""]
    return ["## Curation notes", "", *out] if out else []


def _splits_section(result: CurationResult, fm: dict[str, Any]) -> list[str]:
    container = result.container
    meta = container.experiment_metadata
    sp = fm["splits"]
    shape = (
        f"{sp['n_repeats']} repeat(s) x {sp['n_folds']} fold(s) with seed {sp['random_state']}; "
        f"train {_range(sp['n_train'])} rows, test {_range(sp['n_test'])} rows."
    )
    if sp["time_horizon"] is not None:
        shape += f" Prediction horizon: {sp['time_horizon']} {sp['time_horizon_unit'] or ''}".rstrip() + "."
    table = split_summary(container.dataset, meta.splits, time_on=container.task_metadata.time_on)
    out = ["## Splits", "", meta.splits_comment.strip(), "", shape, ""]
    return out + _maybe_collapsed(f"Show all {len(table)} splits", _table(table), len(table))


def _group_section(result: CurationResult) -> list[str]:
    grouping = result.container.task_metadata.grouping
    if grouping is None:
        return []
    unit = grouping.prediction_unit + (f" ({grouping.aggregation})" if grouping.aggregation else "")
    fields = [
        ("group column", _names(grouping.on)),
        ("labels", grouping.labels),
        ("order inside a group", f"`{grouping.time_on}`" if grouping.time_on else "none"),
        ("prediction unit", unit),
        ("known about a group when predicting", grouping.context),
    ]
    out = ["## Group structure", ""]
    if grouping.definition:
        out += [grouping.definition.strip(), ""]
    out += [_table(pd.DataFrame(fields, columns=["field", "value"]), full=True), ""]
    stats = result.group_stats
    if stats is None:
        return out
    low, median, high = stats.rows_per_group
    rows = [
        ("groups", f"{stats.n_groups:,}"),
        ("rows per group (min / median / max)", f"{low:,} / {median:,.1f} / {high:,}"),
        ("largest group", f"{stats.largest_share:.1%} of the rows"),
        ("test groups per fold", _range({"min": stats.test_groups_per_fold[0], "max": stats.test_groups_per_fold[1]})),
        ("groups of two or more rows with a single label", f"{stats.single_label_share:.1%}"),
    ]
    if stats.neighbour_same_group is not None:
        rows.append(
            (
                "nearest neighbour in the same group",
                f"{stats.neighbour_same_group:.1%} of the rows (chance: {stats.neighbour_chance:.1%})",
            )
        )
    if stats.label_share_by_group is not None:
        rows.append(
            (
                "label variance explained by the group",
                f"{stats.label_share_by_group:.2f} (shuffled groups: {stats.label_share_shuffled:.2f})",
            )
        )
    out += [_table(pd.DataFrame(rows, columns=["statistic", "value"]), full=True), ""]
    out += [
        "The nearest neighbour is computed on the standardised numeric features of a sample of up to "
        f"{group_checks.NEIGHBOUR_SAMPLE_ROWS:,} rows; chance is the share expected if the groups were unrelated to "
        "the features. The model-based diagnostics run with `scripts/v2/group_probes.py`.",
        "",
    ]
    return out


def _decisions_section(result: CurationResult, figures: dict[int, str]) -> list[str]:
    if not result.decisions:
        return []
    out = ["## Decisions", ""]
    for i, decision in enumerate(result.decisions):
        out += [f"### {i + 1}. {decision.title}", "", decision.why.strip(), ""]
        evidence = decision.evidence
        if i in figures:
            out += [f"![{decision.title}]({figures[i]})", ""]
        elif isinstance(evidence, pd.Series):
            out += [_table(evidence.to_frame(), index=True), ""]
        elif isinstance(evidence, pd.DataFrame):
            out += [_table(evidence, index=not isinstance(evidence.index, pd.RangeIndex)), ""]
        elif isinstance(evidence, str) and evidence.strip():
            out += [evidence.strip(), ""]
    return out


def _bundle_checks_section(result: CurationResult) -> list[str]:
    report = result.bundle_report
    ds = result.dataset
    out = [
        "## Bundle checks",
        "",
        f"{len(report.errors)} error(s), {len(report.warnings)} warning(s), {len(report.infos)} info "
        f"({report.n_checks_run} checks run, plus the dataset's own checks).",
        "",
    ]
    for result_ in report.results:
        line = f"- **{result_.severity}** `{result_.slug}`: {_one_line(result_.message)}"
        if result_.hint:
            line += f" (hint: {_one_line(result_.hint)})"
        out.append(line)
    if ds.accepted_check_warnings:
        out += ["", "Accepted on purpose:", ""]
        out += [f"- `{slug}`: {_one_line(reason)}" for slug, reason in ds.accepted_check_warnings.items()]
    out.append("")
    return out


def _data_checks_section(result: CurationResult) -> list[str]:
    out = ["## Data checks", ""]
    titles = {
        "summary": "Feature summary",
        "target": "Target distribution",
        "numeric_stats": "Numeric features",
        "cat_stats": "Categorical features",
    }
    for key, title in titles.items():
        table = result.data_checks.get(key)
        if table is None or len(table) == 0:
            continue
        if isinstance(table, str):  # run_all_checks returns a message instead, e.g. "No numeric features to summarize."
            out += [f"### {title}", "", _one_line(table), ""]
            continue
        out += [f"### {title}", ""]
        out += _maybe_collapsed(
            f"Show the table ({len(table):,} rows)", _table(table, index=key != "summary"), len(table)
        )
    return out


def _build_section(fm: dict[str, Any]) -> list[str]:
    build = fm["build"]
    out = ["## Build", ""]
    if not build:
        return [
            *out,
            "Not built yet. `dataset build` saves the container to the warehouse and records "
            "its UUID, checksum and provenance here.",
            "",
        ]
    rows = list(build.items())
    if fm["build_stale"]:
        rows.append(("stale", f"yes: the definition now gives checksum `{fm['checksum']}`"))
    return [*out, _table(pd.DataFrame(rows, columns=["field", "value"]), full=True), ""]


# --- writing ------------------------------------------------------------------------------------------------


def write_report(result: CurationResult, path: Path | str) -> Path:
    """Render ``result`` and write it to ``path``, keeping the build record of the page it replaces.

    Decision figures are saved as PNGs under ``figures/`` next to it; PNGs of decisions that no longer exist
    are removed.
    """
    path = Path(path)
    figure_dir = path.parent / FIGURE_DIR
    figures: dict[int, str] = {}
    for i, decision in enumerate(result.decisions):
        if hasattr(decision.evidence, "savefig"):
            name = f"decision_{i + 1}_{_slug(decision.title)}.png"
            figure_dir.mkdir(exist_ok=True)
            decision.evidence.savefig(figure_dir / name, dpi=100, bbox_inches="tight", metadata={"Software": None})
            figures[i] = f"{FIGURE_DIR}/{name}"
            _close(decision.evidence)
    if figure_dir.is_dir():
        keep = {Path(f).name for f in figures.values()}
        for png in figure_dir.glob("decision_*.png"):
            if png.name not in keep:
                png.unlink()
    text = render_report(result, previous=read_report(path), figures=figures)
    path.write_text(text)
    return path


# --- helpers ------------------------------------------------------------------------------------------------


def _repo_root(folder: Path) -> Path | None:
    """The repository root that holds both ``folder`` and the curation records, if there is one."""
    root = resolve_curation_root().resolve().parent
    return root if folder.resolve().is_relative_to(root) else None


def _repo_relative(folder: Path) -> str:
    root = _repo_root(folder)
    return folder.resolve().relative_to(root).as_posix() if root else folder.name


def _record_link(ds: AbstractCuratedDataset) -> str | None:
    """A relative link to the curation record of ``ds`` (its own, else the one of the dataset it derives from)."""
    if _repo_root(ds.folder) is None:
        return None
    for name in (ds.unique_name, ds.version_of, ds.raw_data_from):
        record = records_dir() / f"{name}.md" if name else None
        if record is not None and record.is_file():
            rel = Path(os.path.relpath(record.resolve(), ds.folder.resolve())).as_posix()
            return f"[`curation/records/{record.name}`]({rel})"
    return None


def _details(summary: str, body: str) -> list[str]:
    return ["<details>", f"<summary>{summary}</summary>", "", body, "", "</details>", ""]


def _maybe_collapsed(summary: str, table: str, n_rows: int) -> list[str]:
    return _details(summary, table) if n_rows > MAX_OPEN_ROWS else [table, ""]


def _fence(text: str | None, lang: str = "") -> str:
    """``text`` in a fenced code block whose fence is longer than any backtick run inside it."""
    text = (text or "").strip()
    longest = max((len(run) for run in re.findall(r"`+", text)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}{lang}\n{text}\n{fence}"


def _names(columns: Any) -> str:
    columns = [columns] if isinstance(columns, str) else list(columns or [])
    return ", ".join(f"`{c}`" for c in columns)


def _range(bounds: dict[str, int]) -> str:
    low, high = bounds["min"], bounds["max"]
    return f"{low:,}" if low == high else f"{low:,} to {high:,}"


def _close(figure: Any) -> None:
    try:
        import matplotlib.pyplot as plt  # noqa: PLC0415 - only when a decision has a figure
    except ImportError:
        return
    plt.close(figure)


def _slug(text: str) -> str:
    return "_".join("".join(c.lower() if c.isalnum() else " " for c in text).split())[:40]


def _one_line(text: str) -> str:
    return " ".join(str(text).split())


def _cell(value: Any, *, full: bool = False) -> str:
    if isinstance(value, float):
        text = f"{value:.6g}"
    elif isinstance(value, (dt.datetime, pd.Timestamp)):
        text = str(value)
    elif value is None or (not isinstance(value, (list, tuple, dict)) and pd.isna(value)):
        text = ""
    else:
        text = str(value)
    text = _one_line(text).replace("|", "\\|")
    return text if full or len(text) <= MAX_CELL_CHARS else text[: MAX_CELL_CHARS - 1] + "…"


def _table(df: pd.DataFrame, *, index: bool = False, full: bool = False) -> str:
    """Render ``df`` as a GitHub markdown table, truncated to :data:`MAX_TABLE_ROWS` rows.

    Cells are cut to :data:`MAX_CELL_CHARS` characters unless ``full`` (for the short field/value tables).
    """
    if index:
        df = df.reset_index()
    shown = df.head(MAX_TABLE_ROWS)
    header = [_cell(c) for c in shown.columns]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(_cell(v, full=full) for v in row) + " |" for row in shown.itertuples(index=False)]
    if len(df) > len(shown):
        lines.append(f"\n({len(df) - len(shown):,} more rows not shown)")
    return "\n".join(lines)
