"""Rebuild the toy curated container shipped inside `data_foundry.examples`.

This produces a small, fully-formed `CuratedContainer` on disk under
``src/data_foundry/examples/toy_container/<unique_name>/<uuid>/`` so that
the package can offer a runnable end-to-end example after a plain
``pip install data-foundry`` (no warehouse required).

Run from the repo root::

    python scripts/build_toy_container.py
"""

from __future__ import annotations

import shutil
from pathlib import Path

import numpy as np
import pandas as pd
from data_foundry.curation_container import CuratedContainer
from data_foundry.examples import TOY_CONTAINER_UNIQUE_NAME, TOY_CONTAINER_UUID
from data_foundry.schema import (
    DatasetMetadata,
    PredictiveMLSplitsMetadata,
    PredictiveMLTaskMetadata,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
TOY_BASE_DIR = REPO_ROOT / "src" / "data_foundry" / "examples" / "toy_container"


TOY_EXTRA_FILENAME: str = "toy_extra.parquet"
"""File name of the toy extra-artifact shipped next to the toy container."""


def make_toy_dataframe(n_rows: int = 200, rng_seed: int = 0) -> pd.DataFrame:
    """Tiny synthetic binary-classification dataset with a few dtype flavours."""
    rng = np.random.default_rng(rng_seed)
    x_num = rng.normal(size=n_rows).astype("float32")
    x_int = rng.integers(low=0, high=10, size=n_rows).astype("int32")
    x_cat = pd.Categorical(rng.choice(["a", "b", "c"], size=n_rows))
    noise = rng.normal(scale=0.5, size=n_rows)
    # A classification target must be ``category`` dtype — this is the Data Foundry curation
    # contract (see ``dataset_checks.summarize_dataset``), and what consumers (e.g. TabArena's
    # ``convert_curated_container_to_user_task``) rely on. Use string labels like a real curated set.
    target = pd.Categorical(np.where((x_num + 0.3 * x_int + noise) > 0, "pos", "neg"))
    return pd.DataFrame(
        {
            "feat_num": x_num,
            "feat_int": x_int,
            "feat_cat": x_cat,
            "target": target,
        },
    )


def make_toy_extra(n_rows: int = 8, n_cols: int = 4, rng_seed: int = 1) -> pd.DataFrame:
    """Toy extra-artifact parquet — random floats with an arbitrary ``key`` index.

    Stands in for any producer-defined sidecar (e.g. an embedding cache) shipped
    alongside the six core container files.
    """
    rng = np.random.default_rng(rng_seed)
    return pd.DataFrame(
        rng.normal(size=(n_rows, n_cols)).astype("float32"),
        index=pd.Index([f"row_{i}" for i in range(n_rows)], name="key"),
    )


def make_toy_splits(n_rows: int, n_folds: int = 3, rng_seed: int = 0) -> dict:
    """Single-repeat K-fold splits in the same shape `PredictiveMLSplitsMetadata` expects."""
    rng = np.random.default_rng(rng_seed)
    perm = rng.permutation(n_rows)
    fold_indices = np.array_split(perm, n_folds)

    folds: dict[int, tuple[list[int], list[int]]] = {}
    for fold_id, test_idx in enumerate(fold_indices):
        test_idx_sorted = sorted(int(i) for i in test_idx)
        train_idx_sorted = sorted(int(i) for i in perm if i not in set(test_idx))
        folds[fold_id] = (train_idx_sorted, test_idx_sorted)
    return {0: folds}


def main() -> None:
    if TOY_BASE_DIR.exists():
        shutil.rmtree(TOY_BASE_DIR)
    TOY_BASE_DIR.mkdir(parents=True)

    df = make_toy_dataframe()

    dataset_metadata = DatasetMetadata(
        unique_name=TOY_CONTAINER_UNIQUE_NAME,
        dataset_year="2026",
        domain_str="handcrafted",
        dataset_source="Other",
        original_dataset_source_download_link="https://example.com/toy",
        download_description="Synthetic dataset generated by scripts/build_toy_container.py.",
        academic_reference_bibtex="@misc{toy, title={Toy synthetic dataset}, year={2026}}",
        academic_reference_bibtex_key="toy",
        license="CC0-1.0",
        data_tags=["IID"],
        curation_comments=(
            "Tiny synthetic binary-classification dataset shipped inside the data_foundry "
            "package so users can try CuratedContainer.load() right after pip install."
        ),
    )
    task_metadata = PredictiveMLTaskMetadata(
        target_column_name="target",
        problem_type="binary_classification",
        objective_metric_name="roc_auc",
        stratify_on="target",
    )
    splits_metadata = PredictiveMLSplitsMetadata(
        splits_comment="3-fold stratified-ish split over a single repeat (for demonstration).",
        splits=make_toy_splits(n_rows=len(df)),
    )

    container = CuratedContainer(
        dataset=df,
        dataset_metadata=dataset_metadata,
        task_metadata=task_metadata,
        experiment_metadata=splits_metadata,
        uuid=TOY_CONTAINER_UUID,
        version_comment="v1 — initial toy container.",
    )
    save_path = container.save(save_dir=TOY_BASE_DIR)

    extra = make_toy_extra()
    extra.to_parquet(save_path / TOY_EXTRA_FILENAME)

    print(f"Toy container saved to {save_path}")


if __name__ == "__main__":
    main()
